# src/talking_clock_audio/tts_generator.py

"""TTS audio generation using Piper.

Generates audio files from text using Piper TTS voices.
"""

import json
import logging
import wave
from pathlib import Path
from typing import Dict, Any

from piper import PiperVoice

from .phrase_generator import get_all_vocab_with_dedup, generate_phrase_tokens

logger = logging.getLogger(__name__)


def generate_audio_file(text: str, output_path: Path | str, 
                        voice: PiperVoice) -> bool:
    """Generate audio file from text using Piper TTS.
    
    Args:
        text: Text to convert to speech.
        output_path: Path where .wav file should be saved.
        voice: Loaded PiperVoice object.
        
    Returns:
        True if successful, False if failed.
    """
    try:
        with wave.open(str(output_path), 'wb') as wav_file:
            voice.synthesize_wav(text, wav_file)
        
        logger.debug(f"Generated audio: {output_path}")
        return True
        
    except Exception as e:
        logger.error(f"Failed to generate audio for '{text}': {e}")
        return False


def generate_audio_package_with_tts(config: Dict[str, Any], mode: str, 
                                     voice_model_path: Path | str,
                                     output_dir: Path | str = None) -> Dict[str, Any]:
    """Generate audio package with real TTS-generated audio files.
    
    Creates a directory structure with:
    - config.json: Pico-compatible configuration
    - audio/: Directory with real .wav files generated by Piper TTS
    
    Args:
        config: Loaded YAML configuration.
        mode: Mode name (e.g., 'casual', 'broadcast').
        voice_model_path: Path to .onnx voice model file.
        output_dir: Output directory path. If None, generates path from model info.
        
    Returns:
        Dict with statistics including success/failure counts.
    """
    voice_model_path = Path(voice_model_path)
    locale = config['locale']
    
    # Extract voice info from model filename
    # Expected format: locale-voice-quality.onnx (e.g., en_US-lessac-medium.onnx)
    model_filename = voice_model_path.stem  # Gets filename without extension
    
    try:
        # Parse the filename
        parts = model_filename.split('-')
        if len(parts) >= 3:
            voice_name = parts[1]
            quality = parts[2]
        else:
            # Fallback if filename doesn't match expected pattern
            voice_name = 'unknown'
            quality = 'unknown'
    except:
        voice_name = 'unknown'
        quality = 'unknown'
    
    # Generate output directory if not provided
    if output_dir is None:
        output_dir = f"audio/{locale}_{voice_name}_{quality}_{mode}"
    
    output_path = Path(output_dir)
    audio_path = output_path / 'audio'
    
    # Create directories
    output_path.mkdir(parents=True, exist_ok=True)
    audio_path.mkdir(exist_ok=True)
    
    # Load voice model
    logger.info(f"Loading voice model: {voice_model_path}")
    voice = PiperVoice.load(str(voice_model_path))
    
    # Get vocab mapping
    vocab_map, audio_files = get_all_vocab_with_dedup(config)
    
    # Generate audio files
    success_count = 0
    failure_count = 0
    failed_files = []
    
    logger.info(f"Generating {len(audio_files)} audio files with TTS...")
    
    for filename, text in audio_files.items():
        audio_file_path = audio_path / filename
        
        success = generate_audio_file(text, audio_file_path, voice)
        
        if success:
            success_count += 1
        else:
            failure_count += 1
            failed_files.append((filename, text))
            # Create empty placeholder for failed files
            audio_file_path.touch()
    
    # Generate rules for all 1440 time combinations
    rules = []
    for hour in range(24):
        for minute in range(60):
            tokens = generate_phrase_tokens(config, mode, hour, minute)
            if tokens:
                rules.append({
                    'when': {'hour_24': hour, 'minute': minute},
                    'tokens': tokens
                })
    
    # Build JSON structure
    package_config = {
        'locale': config['locale'],
        'mode': mode,
        'voice': voice_name,
        'quality': quality,
        'vocab_files': vocab_map,
        'rules': rules
    }
    
    # Write config.json
    config_file_path = output_path / 'config.json'
    with open(config_file_path, 'w') as f:
        json.dump(package_config, f, indent=2)
    
    # Return statistics
    stats = {
        'output_dir': str(output_path),
        'config_file': str(config_file_path),
        'audio_dir': str(audio_path),
        'rules_count': len(rules),
        'total_audio_files': len(audio_files),
        'success_count': success_count,
        'failure_count': failure_count,
        'failed_files': failed_files
    }
    
    if failure_count > 0:
        logger.warning(f"Failed to generate {failure_count} audio files")
        for filename, text in failed_files:
            logger.warning(f"  {filename}: '{text}'")
    
    logger.info(f"Successfully generated {success_count}/{len(audio_files)} audio files")
    
    return stats
